In [25]:
"""
numpy：Python 科学计算库
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 使用 array 函数，通过 list 创建数据对象
arr1 = np.array([1, 2, 3, 4, 5])
arr1

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2


# arange 函数：指定取值范围和跨度创建数组对象，左闭右开
arr3 = np.arange(0, 20, 2)
arr3

arr4 = np.linspace(-1, 1, 11)
arr4

# 数组的索引计算
arr5 = np.arange(1, 10)
arr5

print(arr5[0], arr5[arr5.size - 1])
print(arr5[-arr5.size], arr5[-1])

arr6 = np.array([[1, 2, 3], [10, 11, 12], [7, 8, 9]])
arr6


1 9
1 9


array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [11]:
arr6[0][0]

np.int64(1)

In [12]:
print(arr6[2][2])

9


In [16]:
arr6[:2, 1:]    # 第一个逗号控制行的范围，第二个逗号控制列的范围

array([[ 2,  3],
       [11, 12]])

In [17]:
arr6[2, :]

array([7, 8, 9])

In [18]:
arr6[:, :2]

array([[ 1,  2],
       [10, 11],
       [ 7,  8]])

In [19]:
arr6[:, :]

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [21]:
arr6[::2, ::2]

array([[1, 3],
       [7, 9]])

In [22]:
arr6[::-2, ::-2]

array([[9, 7],
       [3, 1]])

In [26]:
arr6[[0, 2]]    # 使用数组作为索引

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
arr6[[0, 2], [1, 2]]

array([2, 9])

In [28]:
arr6[[0, 2], 1]

array([2, 8])